### ISSUE TITLE
bad link?

### ISSUE THREAD

**Issue by cicorias** [noodlefrenzy/NikkeiAISummit2019#1]
I think 
```html
<a href="https://aka.ms/iotdevops" rel="nofollow">My Team's Living Guidance Document</a>
```
was meant for PlayBook?

**Comment by noodlefrenzy** [comment]
Updated link to deep-link into the content as suggested: https://dev.azure.com/iotedgedo/iotedgedoproj/_git/IoT_DevOps_Fundamentals

Please reopen if that's not working.
